Update main.py to be compatible with Windows
after running opendevin by the command: 
```
set PYTHONPATH=%cd%
python opendevin\main.py -d .\workspace\ -i 100 -t "Write a bash script that prints 'hello world'"

```
we got error that: 
```
\opendevin\opendevin\main.py", line 1, in <module>
    from opendevin.agent import Agent
ModuleNotFoundError: No module named 'opendevin'
```
so when I modified it and replaced "opendevin.agent"   with 
" .agent "  it works on this file because the package is locally on the folder so we need to import it as path by adding '.' before the package name and the modification should be on all scripts that need to call packages